/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","cs",{euro:"Znak eura",lsquo:"Počáteční uvozovka jednoduchá",rsquo:"Koncová uvozovka jednoduchá",ldquo:"Počáteční uvozovka dvojitá",rdquo:"Koncová uvozovka dvojitá",ndash:"En pomlčka",mdash:"Em pomlčka",iexcl:"Obrácený vykřičník",cent:"Znak centu",pound:"Znak libry",curren:"Znak měny",yen:"Znak jenu",brvbar:"Přerušená svislá čára",sect:"Znak oddílu",uml:"Přehláska",copy:"Znak copyrightu",ordf:"Ženský indikátor rodu",laquo:"Znak dvojitých lomených uvozovek vlevo",
not:"Logistický zápor",reg:"Znak registrace",macr:"Pomlčka nad",deg:"Znak stupně",sup2:"Dvojka jako horní index",sup3:"Trojka jako horní index",acute:"Čárka nad vpravo",micro:"Znak mikro",para:"Znak odstavce",middot:"Tečka uprostřed",cedil:"Ocásek vlevo",sup1:"Jednička jako horní index",ordm:"Mužský indikátor rodu",raquo:"Znak dvojitých lomených uvozovek vpravo",frac14:"Obyčejný zlomek jedna čtvrtina",frac12:"Obyčejný zlomek jedna polovina",frac34:"Obyčejný zlomek tři čtvrtiny",iquest:"Znak obráceneho otazníku",
Agrave:"Velke písmeno latinky A s čárkou nad vlevo",Aacute:"Velke písmeno latinky A s čárkou nad vpravo",Acirc:"Velke písmeno latinky A s vokáněm",Atilde:"Velke písmeno latinky A s tildou",Auml:"Velke písmeno latinky A s dvěma tečkami",Aring:"Velke písmeno latinky A s kroužkem nad",AElig:"Velke písmeno latinky Ae",Ccedil:"Velke písmeno latinky C s ocáskem vlevo",Egrave:"Velke písmeno latinky E s čárkou nad vlevo",Eacute:"Velke písmeno latinky E s čárkou nad vpravo",Ecirc:"Velke písmeno latinky E s vokáněm",
Euml:"Velke písmeno latinky E s dvěma tečkami",Igrave:"Velke písmeno latinky I s čárkou nad vlevo",Iacute:"Velke písmeno latinky I s čárkou nad vpravo",Icirc:"Velke písmeno latinky I s vokáněm",Iuml:"Velke písmeno latinky I s dvěma tečkami",ETH:"Velke písmeno latinky Eth",Ntilde:"Velke písmeno latinky N s tildou",Ograve:"Velke písmeno latinky O s čárkou nad vlevo",Oacute:"Velke písmeno latinky O s čárkou nad vpravo",Ocirc:"Velke písmeno latinky O s vokáněm",Otilde:"Velke písmeno latinky O s tildou",
Ouml:"Velke písmeno latinky O s dvěma tečkami",times:"Znak násobení",Oslash:"Velke písmeno latinky O přeškrtnute",Ugrave:"Velke písmeno latinky U s čárkou nad vlevo",Uacute:"Velke písmeno latinky U s čárkou nad vpravo",Ucirc:"Velke písmeno latinky U s vokáněm",Uuml:"Velke písmeno latinky U s dvěma tečkami",Yacute:"Velke písmeno latinky Y s čárkou nad vpravo",THORN:"Velke písmeno latinky Thorn",szlig:"Male písmeno latinky ostre s",agrave:"Male písmeno latinky a s čárkou nad vlevo",aacute:"Male písmeno latinky a s čárkou nad vpravo",
acirc:"Male písmeno latinky a s vokáněm",atilde:"Male písmeno latinky a s tildou",auml:"Male písmeno latinky a s dvěma tečkami",aring:"Male písmeno latinky a s kroužkem nad",aelig:"Male písmeno latinky ae",ccedil:"Male písmeno latinky c s ocáskem vlevo",egrave:"Male písmeno latinky e s čárkou nad vlevo",eacute:"Male písmeno latinky e s čárkou nad vpravo",ecirc:"Male písmeno latinky e s vokáněm",euml:"Male písmeno latinky e s dvěma tečkami",igrave:"Male písmeno latinky i s čárkou nad vlevo",iacute:"Male písmeno latinky i s čárkou nad vpravo",
icirc:"Male písmeno latinky i s vokáněm",iuml:"Male písmeno latinky i s dvěma tečkami",eth:"Male písmeno latinky eth",ntilde:"Male písmeno latinky n s tildou",ograve:"Male písmeno latinky o s čárkou nad vlevo",oacute:"Male písmeno latinky o s čárkou nad vpravo",ocirc:"Male písmeno latinky o s vokáněm",otilde:"Male písmeno latinky o s tildou",ouml:"Male písmeno latinky o s dvěma tečkami",divide:"Znak dělení",oslash:"Male písmeno latinky o přeškrtnute",ugrave:"Male písmeno latinky u s čárkou nad vlevo",
uacute:"Male písmeno latinky u s čárkou nad vpravo",ucirc:"Male písmeno latinky u s vokáněm",uuml:"Male písmeno latinky u s dvěma tečkami",yacute:"Male písmeno latinky y s čárkou nad vpravo",thorn:"Male písmeno latinky thorn",yuml:"Male písmeno latinky y s dvěma tečkami",OElig:"Velká ligatura latinky OE",oelig:"Malá ligatura latinky OE",372:"Velke písmeno latinky W s vokáněm",374:"Velke písmeno latinky Y s vokáněm",373:"Male písmeno latinky w s vokáněm",375:"Male písmeno latinky y s vokáněm",sbquo:"Dolní 9 uvozovka jednoduchá",
8219:"Horní obrácená 9 uvozovka jednoduchá",bdquo:"Dolní 9 uvozovka dvojitá",hellip:"Trojtečkový úvod",trade:"Obchodní značka",9658:"Černý ukazatel směřující vpravo",bull:"Kolečko",rarr:"Šipka vpravo",rArr:"Dvojitá šipka vpravo",hArr:"Dvojitá šipka vlevo a vpravo",diams:"Černe piky",asymp:"Teměř se rovná"});