/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","hu",{euro:"Euró jel",lsquo:"Bal szimpla idezőjel",rsquo:"Jobb szimpla idezőjel",ldquo:"Bal dupla idezőjel",rdquo:"Jobb dupla idezőjel",ndash:"Rövid gondolatjel",mdash:"Hosszú gondolatjel",iexcl:"Fordított felkiáltójel",cent:"Cent jel",pound:"Font jel",curren:"Valuta jel",yen:"Yen jel",brvbar:"Hosszú kettőspont",sect:"Paragrafus jel",uml:"Kettős hangzó jel",copy:"Szerzői jog jel",ordf:"Női sorrend mutatója",laquo:"Balra mutató duplanyíl",not:"Felteteles kötőjel",
reg:"Bejegyzett vedjegy jele",macr:"Hosszúsági jel",deg:"Fok jel",sup2:"Negyzeten jel",sup3:"Köbön jel",acute:"Éles ekezet",micro:"Mikro-jel",para:"Bekezdes jel",middot:"Közep pont",cedil:"Cedille",sup1:"Elsőn jel",ordm:"Ferfi sorrend mutatója",raquo:"Jobbra mutató duplanyíl",frac14:"Egy negyed jel",frac12:"Egy ketted jel",frac34:"Három negyed jel",iquest:"Fordított kerdőjel",Agrave:"Latin nagy A fordított ekezettel",Aacute:"Latin nagy A normál ekezettel",Acirc:"Latin nagy A hajtott ekezettel",Atilde:"Latin nagy A hullámjellel",
Auml:"Latin nagy A kettőspont ekezettel",Aring:"Latin nagy A gyűrű ekezettel",AElig:"Latin nagy Æ betű",Ccedil:"Latin nagy C cedillával",Egrave:"Latin nagy E fordított ekezettel",Eacute:"Latin nagy E normál ekezettel",Ecirc:"Latin nagy E hajtott ekezettel",Euml:"Latin nagy E dupla kettőspont ekezettel",Igrave:"Latin nagy I fordított ekezettel",Iacute:"Latin nagy I normál ekezettel",Icirc:"Latin nagy I hajtott ekezettel",Iuml:"Latin nagy I kettőspont ekezettel",ETH:"Latin nagy Eth betű",Ntilde:"Latin nagy N hullámjellel",
Ograve:"Latin nagy O fordított ekezettel",Oacute:"Latin nagy O normál ekezettel",Ocirc:"Latin nagy O hajtott ekezettel",Otilde:"Latin nagy O hullámjellel",Ouml:"Latin nagy O kettőspont ekezettel",times:"Szorzás jel",Oslash:"Latin O betű áthúzással",Ugrave:"Latin nagy U fordított ekezettel",Uacute:"Latin nagy U normál ekezettel",Ucirc:"Latin nagy U hajtott ekezettel",Uuml:"Latin nagy U kettőspont ekezettel",Yacute:"Latin nagy Y normál ekezettel",THORN:"Latin nagy Thorn betű",szlig:"Latin kis s betű",
agrave:"Latin kis a fordított ekezettel",aacute:"Latin kis a normál ekezettel",acirc:"Latin kis a hajtott ekezettel",atilde:"Latin kis a hullámjellel",auml:"Latin kis a kettőspont ekezettel",aring:"Latin kis a gyűrű ekezettel",aelig:"Latin kis æ betű",ccedil:"Latin kis c cedillával",egrave:"Latin kis e fordított ekezettel",eacute:"Latin kis e normál ekezettel",ecirc:"Latin kis e hajtott ekezettel",euml:"Latin kis e dupla kettőspont ekezettel",igrave:"Latin kis i fordított ekezettel",iacute:"Latin kis i normál ekezettel",
icirc:"Latin kis i hajtott ekezettel",iuml:"Latin kis i kettőspont ekezettel",eth:"Latin kis eth betű",ntilde:"Latin kis n hullámjellel",ograve:"Latin kis o fordított ekezettel",oacute:"Latin kis o normál ekezettel",ocirc:"Latin kis o hajtott ekezettel",otilde:"Latin kis o hullámjellel",ouml:"Latin kis o kettőspont ekezettel",divide:"Osztásjel",oslash:"Latin kis o betű áthúzással",ugrave:"Latin kis u fordított ekezettel",uacute:"Latin kis u normál ekezettel",ucirc:"Latin kis u hajtott ekezettel",
uuml:"Latin kis u kettőspont ekezettel",yacute:"Latin kis y normál ekezettel",thorn:"Latin kis thorn jel",yuml:"Latin kis y kettőspont ekezettel",OElig:"Latin nagy OE-jel",oelig:"Latin kis oe-jel",372:"Latin nagy W hajtott ekezettel",374:"Latin nagy Y hajtott ekezettel",373:"Latin kis w hajtott ekezettel",375:"Latin kis y hajtott ekezettel",sbquo:"Nyitó nyomdai szimpla idezőjel",8219:"Záró nyomdai záró idezőjel",bdquo:"Nyitó nyomdai dupla idezőjel",hellip:"Három pont",trade:"Kereskedelmi vedjegy jele",
9658:"Jobbra mutató fekete mutató",bull:"Golyó",rarr:"Jobbra mutató nyíl",rArr:"Jobbra mutató duplanyíl",hArr:"Bal-jobb duplanyíl",diams:"Fekete gyemánt jel",asymp:"Majdnem egyenlő jel"});