/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sk",{euro:"Znak eura",lsquo:"Ľavá jednoduchá úvodzovka",rsquo:"Pravá jednoduchá úvodzovka",ldquo:"Pravá dvojitá úvodzovka",rdquo:"Pravá dvojitá úvodzovka",ndash:"En pomlčka",mdash:"Em pomlčka",iexcl:"Obrátený výkričník",cent:"Znak centu",pound:"Znak libry",curren:"Znak meny",yen:"Znak jenu",brvbar:"Prerušená zvislá čiara",sect:"Znak odseku",uml:"Prehláska",copy:"Znak copyrightu",ordf:"Ženský indikátor rodu",laquo:"Znak dvojitých lomených úvodzoviek vľavo",not:"Logistický zápor",
reg:"Znak registrácie",macr:"Pomlčka nad",deg:"Znak stupňa",sup2:"Dvojka ako horný index",sup3:"Trojka ako horný index",acute:"Dĺžeň",micro:"Znak mikro",para:"Znak odstavca",middot:"Bodka uprostred",cedil:"Chvost vľavo",sup1:"Jednotka ako horný index",ordm:"Mužský indikátor rodu",raquo:"Znak dvojitých lomených úvodzoviek vpravo",frac14:"Obyčajný zlomok jedna štvrtina",frac12:"Obyčajný zlomok jedna polovica",frac34:"Obyčajný zlomok tri štvrtiny",iquest:"Otočený otáznik",Agrave:"Veľke písmeno latinky A s accentom",
Aacute:"Veľke písmeno latinky A s dĺžňom",Acirc:"Veľke písmeno latinky A s mäkčeňom",Atilde:"Veľke písmeno latinky A s tildou",Auml:"Veľke písmeno latinky A s dvoma bodkami",Aring:"Veľke písmeno latinky A s krúžkom nad",AElig:"Veľke písmeno latinky Æ",Ccedil:"Veľke písmeno latinky C s chvostom vľavo",Egrave:"Veľke písmeno latinky E s accentom",Eacute:"Veľke písmeno latinky E s dĺžňom",Ecirc:"Veľke písmeno latinky E s mäkčeňom",Euml:"Veľke písmeno latinky E s dvoma bodkami",Igrave:"Veľke písmeno latinky I s accentom",
Iacute:"Veľke písmeno latinky I s dĺžňom",Icirc:"Veľke písmeno latinky I s mäkčeňom",Iuml:"Veľke písmeno latinky I s dvoma bodkami",ETH:"Veľke písmeno latinky Eth",Ntilde:"Veľke písmeno latinky N s tildou",Ograve:"Veľke písmeno latinky O s accentom",Oacute:"Veľke písmeno latinky O s dĺžňom",Ocirc:"Veľke písmeno latinky O s mäkčeňom",Otilde:"Veľke písmeno latinky O s tildou",Ouml:"Veľke písmeno latinky O s dvoma bodkami",times:"Znak násobenia",Oslash:"Veľke písmeno latinky O preškrtnute",Ugrave:"Veľke písmeno latinky U s accentom",
Uacute:"Veľke písmeno latinky U s dĺžňom",Ucirc:"Veľke písmeno latinky U s mäkčeňom",Uuml:"Veľke písmeno latinky U s dvoma bodkami",Yacute:"Veľke písmeno latinky Y s dĺžňom",THORN:"Veľke písmeno latinky Thorn",szlig:"Male písmeno latinky ostre s",agrave:"Male písmeno latinky a s accentom",aacute:"Male písmeno latinky a s dĺžňom",acirc:"Male písmeno latinky a s mäkčeňom",atilde:"Male písmeno latinky a s tildou",auml:"Male písmeno latinky a s dvoma bodkami",aring:"Male písmeno latinky a s krúžkom nad",
aelig:"Male písmeno latinky æ",ccedil:"Male písmeno latinky c s chvostom vľavo",egrave:"Male písmeno latinky e s accentom",eacute:"Male písmeno latinky e s dĺžňom",ecirc:"Male písmeno latinky e s mäkčeňom",euml:"Male písmeno latinky e s dvoma bodkami",igrave:"Male písmeno latinky i s accentom",iacute:"Male písmeno latinky i s dĺžňom",icirc:"Male písmeno latinky i s mäkčeňom",iuml:"Male písmeno latinky i s dvoma bodkami",eth:"Male písmeno latinky eth",ntilde:"Male písmeno latinky n s tildou",ograve:"Male písmeno latinky o s accentom",
oacute:"Male písmeno latinky o s dĺžňom",ocirc:"Male písmeno latinky o s mäkčeňom",otilde:"Male písmeno latinky o s tildou",ouml:"Male písmeno latinky o s dvoma bodkami",divide:"Znak delenia",oslash:"Male písmeno latinky o preškrtnute",ugrave:"Male písmeno latinky u s accentom",uacute:"Male písmeno latinky u s dĺžňom",ucirc:"Male písmeno latinky u s mäkčeňom",uuml:"Male písmeno latinky u s dvoma bodkami",yacute:"Male písmeno latinky y s dĺžňom",thorn:"Male písmeno latinky thorn",yuml:"Male písmeno latinky y s dvoma bodkami",
OElig:"Veľká ligatúra latinky OE",oelig:"Malá ligatúra latinky OE",372:"Veľke písmeno latinky W s mäkčeňom",374:"Veľke písmeno latinky Y s mäkčeňom",373:"Male písmeno latinky w s mäkčeňom",375:"Male písmeno latinky y s mäkčeňom",sbquo:"Dolná jednoduchá 9-úvodzovka",8219:"Horná jednoduchá otočená 9-úvodzovka",bdquo:"Dolná dvojitá 9-úvodzovka",hellip:"Trojbodkový úvod",trade:"Znak ibchodnej značky",9658:"Čierny ukazovateľ smerujúci vpravo",bull:"Kruh",rarr:"Šípka vpravo",rArr:"Dvojitá šipka vpravo",
hArr:"Dvojitá šipka vľavo a vpravo",diams:"Čierne piky",asymp:"Skoro sa rovná"});